package chronosacaria.mcda.effects;

public enum ArmorEffectID {
    FIRE_RESISTANCE,
    FLUID_FREEZING,
    HASTE,
    HERO_OF_THE_VILLAGE,
    HUNGER,
    INVISIBILITY,
    LUCK,
    NIMBLE_TURTLE_EFFECTS,
    NO_FALL_DAMAGE,
    PIGLIN_FOOLING,
    SPIDER_CLIMBING,
    SPRINTING,
    WATER_BREATHING,
    WITHERED
}
