package chronosacaria.mcda.effects;

public enum ArmorEffectID {
    FIRE_RESISTANCE,
    FLUID_FREEZING,
    HASTE,
    HERO_OF_THE_VILLAGE,
    HUNGER,
    INVISIBILITY,
    LEADER_OF_THE_PACK,
    LUCK,
    NIMBLE_TURTLE_EFFECTS,
    NO_FALL_DAMAGE,
    PIGLIN_FOOLING,
    SHULKER_LIKE,
    SPIDER_CLIMBING,
    SPRINTING,
    TITAN_SHROUD_EFFECTS,
    WATER_BREATHING,
    WITHERED
}
